static int STATUS_OK = 0;
static int STATUS_ERROR = 1;
static int STATUS_QUIT = 2;
static int STATUS_PASS = 3;

static char filePath[1024];
	
static char goodbye[] = "221-Thank you for using the FTP service.\r\n221-Goodbye.\r\n";
static char no_user[] = "332 Not logged in.\r\n";
static char user_ok[] = "331 Guest login ok, send your complete e-mail address as password.\r\n";
static char user_fail[] = "530 User cannot log in.\r\n";
static char password_ok[] = "230-Welcome to my FTP~\r\n230-Guest login ok, access restrictions apply.\r\n";
static char system_inf[] = "215 UNIX Type: L8\r\n";
static char type_ok[] = "200 Type set to I.\r\n";
static char type_error[] = "504 Command not implemented for the specified argument.\r\n";
static char cwd_ok[] = "200 Your working directory is switched to ";
static char cwd_fail[] = "504 Your argument is wrong or such directory does not exist. Try to delete '.'s.\r\n";
static char cdup_fail[] = "502 You are in the toppest directory.\r\n";
static char mkd_ok[] = "257 Folder created.\r\n";
static char mkd_fail[] = "553 Requested action not taken. File name not allowed.\r\n";
static char mkd_fail_2[] = "550-Requested action not taken. Directory unavailable (e.g. no access).\r\n";
static char mkd_has_same[] = "553 Requested action not taken. Its name is as same as an another folder.\r\n";
static char dele_ok[] = "250 Delete file success.\r\n";
static char dele_fail[] = "550-Requested action not taken. File unavailable(e.g. file not found, no access).\r\n";
static char pasv_ok[] = "227 Entering Passive Mode ";
static char pasv_fail[] = "425 Can't open data connection.\r\n";
static char port_ok[] = "200 PORT command successful.\r\n";
static char no_pasv_port[] = "503 You must input PASV command or PORT command before you input RETR or STOR.\r\n";
static char send_type_bin[] = "150 Opening BINARY mode data connection for ";
static char send_data_ok[] = "226 Transfer complete.\r\n";
static char send_data_fail[] = "550-Requested action not taken. File unavailable (e.g. file not found, no access).\r\n550-You can try 'PASV' command again.\r\n";
static char no_such_command[] = "500 No such command.\r\n";
